- name: Stop k3s
  systemd:
    name: k3s
    state: stopped
  failed_when: false

- name: Download K3s installation script
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s-install.sh
    mode: '0755'

- name: Start K3s
  environment:
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
    INSTALL_K3S_EXEC: "server {{ server_init_args }}"
  command: sh /tmp/k3s-install.sh
  args:
    creates: /usr/local/bin/k3s

- name: Wait for K3s to start
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token
    state: present
    delay: 10
    timeout: 300

- name: Ensure K3s service is enabled and started
  systemd:
    name: k3s
    state: started
    enabled: yes
  register: k3s_service_status
  until: k3s_service_status is success
  retries: 5
  delay: 5
