---
- name: Install K3s 
  hosts: all
  become: yes
  tasks:
    - name: Install container-selinux
      dnf:
        name: container-selinux
        state: present
    
    - name: Install K3s SELinux policy
      dnf:
        name: https://rpm.rancher.io/k3s/stable/common/centos/8/noarch/k3s-selinux-1.5-1.el8.noarch.rpm
        state: present
        disable_gpg_check: yes

    #    - name: Set SELinux to disabled state
    #      ansible.posix.selinux:
    #        state: disabled

    - name: Disable SELinux
      selinux:
        state: disabled

    - name: Reboot the system
      reboot:

    - name: Download K3s installation script
      get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s-install.sh
        mode: '0755'

    - name: Run K3s installation script
      environment:
        INSTALL_K3S_VERSION: "{{ k3s_version }}"
        #INSTALL_K3S_SKIP_SELINUX_RPM: "true"
        INSTALL_K3S_EXEC: "server --container-runtime-endpoint unix:///run/containerd/containerd.sock"
      command: sh /tmp/k3s-install.sh

    - name: Ensure K3s is running
      systemd:
        name: k3s
        state: started
        enabled: yes
